language: go
go:
- master
#install:
#- go get golang.org/x/tools/cmd/cover
#- go get github.com/mattn/goveralls
#script:
#- go test -v -covermode=count -coverprofile=coverage.out
#- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN"
before_deploy:
- "./compile.sh"
- ls
- pwd 
deploy:
  provider: releases
  api_key:
    secure: vIq3WGL3RPhqE583zzrO1db73pmfkFtFfLbsHPtHFwLjNNxjjO3IOuS6TsJu3ZMYshseZkRj1B7fmsBAXjchNVwaKvz2pyX8euU/TFEP5tlIag1Uh5/guJvWI3mRdCE/AXjyIqAVzjyqnrFWIP5OQ65di7yelL3uAt6xo3/gESpfvrhrrOtH3ENBn0jnptFkCpJMMHHe1MptmBMgP87x5rJX1mIPHypLVp7Z4LOvA2IAzL34yN1sql2Td0zItSLGhAS+pViYdsSP6mgCi3vkiQxZ4oWBoUf/b8GN202FQofV78Fy/P3X9vmwp3g6MD8tj2xhXfQmVVDX1hpDOuC8PQpU0v23vTLgFgHRG6EQI/tPvqa+rgoTpGsLtSJpkv787VfVfMRTBUBVZJg6Of44cGPQj+JXCML3Iczfn7OyWd0goytvHXdjgNFkhoAPEDXQRheYDMh0nlFxwFv+S4M6N5ZgWh/81NdHl17eJ5g7cGwQzli0eABra2NriNBzPiARSewtl46aIZlQvMz2v6M7+G/HHI1vzablsnAC+DheWo9CXj5lWJzTau+JB75dp1swgBONZUloyl1jAmTBr6OVPAD2KxFVYzuvbYUQy3UvMxdibEl8ATWmM+2AZfBztYd96e0E7axwVMJq8Kw9rwSTkHQyhMJ+K4TpIgGNHaZFz4E=
  file: "./bin/*"
  skip_cleanup: true
#  on:
#    tags: true
env:
  COVERALLS_TOKEN: VZATjZzePvtZV1qPaa/JUcZyQ+hMh50UO9asPmhQbyerDhr3XUPJKNejjkkzUMfBQ+Az3JKRExH6buJ+cXEIlTirQauSXCCi3kR90c0DaaZFUrW2z5dd4G94fk5nMc7AQ/bK1hfTpbjLroffTCruPS+z+BjVu8HKshaerPL+EpupF/GfSd/HtBWVLb0MTK7Cm4OkBBtjgIyUpCZr+9jFQLsnXFDMOwG85HVJ91QD+Y8f9fTuNxh3Sf+C15LyX92or8Pcv6t/TTWnC55rWsCW57Wk3R2KmFnV7SGv9TC46w/xpc6u13s4L9tHv5lLLfu/OO0Soj/xuv4llBSP8NWHVi1/McI/A+S0XgQtJmhg+mU0cVCE/nI9Ev0mJ4Zpd5mle/5aTM+TJj8P0QfacL3Iox+2ixPIOOwWlL6xGjuLujVRLXriN1mE/wgNhWhElaskXTRMoMdMS8+182/QNhGp662DilRBrH8GCVwXLgUVj3PlwWtb+04Lw4XppctYn3ZtB7JZZcfS5QYA1PgrlAJayvkghSvhJaVQbiASOKUk4dNpGf4vMy3k/3PDYupMGGrGqDn1n4Rgsv4t/gNViVDp0zh4GN8fRaAKAUnA16pyNqQMS2SszoWEWsszCib0N5mT/Vv4iyojZb3edHjKUVIoGmCnVAHvxkgDBUxiSQN3fwQ=
