---
######## Params influxDB necessary if true
  influxDBActivated: "false"
  influxDBServer: "localhost"
  influxDBServerPort: "8086"
  influxDBUsername: "root"
  influxDBPassword: "root"
  influxDBDatabase: "bloomsky"
######## If true display informations on console
  consoleActivated: "false"
######## If true display informations on webpage
  hTTPActivated: "true"
  hTTPPort : ":1111"
######## Refresh time, be not to small because you are blocked by openweather and bloomsky (in second)
  refreshTimer: "60"
######## Params for bloomsky
# Normally don't change
  bloomskyURL: "https://api.bloomsky.com/api/skydata/"
# the key, it's free : https://dashboard.bloomsky.com/
  bloomskyAccessToken: "yourtoken"
# 1 info  -> 4 trace
  logLevel: 4
#########
  mock: false
