---
  main:
######## Params for bloomsky
    bloomsky:
 # Normally don't change
      url: "https://api.bloomsky.com/api/skydata/"
# the key, it's free : https://dashboard.bloomsky.com/
      token: "yourtoken"
# language (en-us, fr)
    language : en-us
######## Refresh time, be not to small because you are blocked by openweather and bloomsky (in second)
    refreshTimer: "70"
# panic,fatal,error,warning,info,debug:
    log:
      level: "debug"
      file: "bloomskylog"
# to use the code in offline mode put mock: true
    mock: false
# use template, static file in folder not in bundled
    dev: false
# use web socket secure by defaut use web socket non secure (necessary to put traefik front the webserver)
    wss: false
#what the hell 
    historyActivated: false
##########
  outputs:
    console:
          activated: true
    web:
          activated: true
          port : ":1111"
          secureport : ":1112"
    influxdb:
          activated: false
          server: "localhost"
          port: "8086"
          username: "root"
          password: "root"
          database: "bloomsky"
